// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors
// SPDX-FileCopyrightText: 2025-2026 Andrey Kolkov and GoGPU Contributors

//go:build !cgo && !android && goffi_musl && !goffi_universal && arm64

package fakecgo

//go:cgo_import_dynamic goffi_malloc malloc "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_free free "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_setenv setenv "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_unsetenv unsetenv "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_sigfillset sigfillset "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_nanosleep nanosleep "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_abort abort "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_sigaltstack sigaltstack "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_attr_init pthread_attr_init "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_create pthread_create "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_detach pthread_detach "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_sigmask pthread_sigmask "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_self pthread_self "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_attr_getstacksize pthread_attr_getstacksize "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_attr_setstacksize pthread_attr_setstacksize "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_attr_destroy pthread_attr_destroy "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_mutex_lock pthread_mutex_lock "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_mutex_unlock pthread_mutex_unlock "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_cond_broadcast pthread_cond_broadcast "libc.musl-aarch64.so.1"
//go:cgo_import_dynamic goffi_pthread_setspecific pthread_setspecific "libc.musl-aarch64.so.1"
