// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors
// SPDX-FileCopyrightText: 2025-2026 Andrey Kolkov and GoGPU Contributors

//go:build !cgo

package fakecgo

//go:cgo_import_dynamic goffi_malloc malloc "libc.so.7"
//go:cgo_import_dynamic goffi_free free "libc.so.7"
//go:cgo_import_dynamic goffi_setenv setenv "libc.so.7"
//go:cgo_import_dynamic goffi_unsetenv unsetenv "libc.so.7"
//go:cgo_import_dynamic goffi_sigfillset sigfillset "libc.so.7"
//go:cgo_import_dynamic goffi_nanosleep nanosleep "libc.so.7"
//go:cgo_import_dynamic goffi_abort abort "libc.so.7"
//go:cgo_import_dynamic goffi_sigaltstack sigaltstack "libc.so.7"
//go:cgo_import_dynamic goffi_pthread_attr_init pthread_attr_init "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_create pthread_create "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_detach pthread_detach "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_sigmask pthread_sigmask "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_self pthread_self "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_get_stacksize_np pthread_get_stacksize_np "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_attr_getstacksize pthread_attr_getstacksize "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_attr_setstacksize pthread_attr_setstacksize "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_attr_destroy pthread_attr_destroy "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_mutex_lock pthread_mutex_lock "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_mutex_unlock pthread_mutex_unlock "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_cond_broadcast pthread_cond_broadcast "libpthread.so"
//go:cgo_import_dynamic goffi_pthread_setspecific pthread_setspecific "libpthread.so"
