// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors
// SPDX-FileCopyrightText: 2025-2026 Andrey Kolkov and GoGPU Contributors

//go:build !cgo

package fakecgo

//go:cgo_import_dynamic goffi_malloc malloc "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_free free "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_setenv setenv "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_unsetenv unsetenv "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_sigfillset sigfillset "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_nanosleep nanosleep "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_abort abort "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_sigaltstack sigaltstack "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_attr_init pthread_attr_init "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_create pthread_create "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_detach pthread_detach "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_sigmask pthread_sigmask "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_self pthread_self "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_get_stacksize_np pthread_get_stacksize_np "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_attr_getstacksize pthread_attr_getstacksize "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_attr_setstacksize pthread_attr_setstacksize "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_attr_destroy pthread_attr_destroy "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_mutex_lock pthread_mutex_lock "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_mutex_unlock pthread_mutex_unlock "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_cond_broadcast pthread_cond_broadcast "/usr/lib/libSystem.B.dylib"
//go:cgo_import_dynamic goffi_pthread_setspecific pthread_setspecific "/usr/lib/libSystem.B.dylib"
